// THROWAWAY UI PROTOTYPE: compare a journal desk, chronological scroll, and focused writing at /prototype?variant=A|B|C.
import { useCallback, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import { BookOpen, CalendarDays, Bookmark, Search, Plus, ArrowUpRight, ChevronLeft, ChevronRight, Sprout, Settings, Cloud, Download, Upload, X, Feather, Sun, CloudRain, Leaf, ArrowLeft, Pencil, Trash2, Check, WifiOff, Menu, LogOut, Mail, LayoutGrid, List, Heart, RefreshCw, MonitorSmartphone } from 'lucide-react';
import type { Session } from '@supabase/supabase-js';
import { registerSW } from 'virtual:pwa-register';
import { type Entry, entryValid, localDate, moods, seeds } from './data';
import { Editor } from './Editor';
import { supabase } from './supabase';
const STORE='ephemera-prototype-entries-v1';
type View='all'|'calendar'|'favorites'|'moods';
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
const variants=['A','B','C'];
const variantNames=['日记书桌','时光长卷','专注书写'];
function readEntries(){try{const text=localStorage.getItem(STORE);if(!text)return {entries:seeds,error:''};const data:unknown=JSON.parse(text);if(Array.isArray(data)&&data.every(entryValid))return {entries:data as Entry[],error:''};return {entries:[],error:'本机日记格式异常，原数据已保留。请先在设置中导出原始备份。'}}catch{return {entries:[],error:'无法读取本机日记。请检查浏览器存储权限，或导出原始备份。'}}}
function Botanical({small=false}:{small?:boolean}){return <svg className={small?'botanical small':'botanical'} viewBox="0 0 320 290" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="1.1"><path d="M138 293C159 227 175 155 153 54M159 196C213 163 231 110 251 66M159 211C113 175 98 137 73 102M166 150C195 122 197 81 199 42M145 268C195 245 227 212 258 185"/><path d="M153 55C113 29 125 4 128 7C167 20 161 39 153 55ZM160 95C112 90 116 59 115 57C151 57 167 77 160 95ZM165 128C135 122 115 105 122 88C154 88 166 109 165 128ZM163 151C185 133 187 105 176 97C155 107 153 134 163 151ZM164 185C120 177 117 158 120 145C154 144 166 163 164 185ZM196 159C222 164 245 146 242 134C214 132 200 145 196 159ZM221 122C201 102 208 78 218 74C238 92 229 111 221 122ZM240 90C267 86 281 64 273 53C250 57 239 70 240 90ZM250 66C232 44 245 26 249 21C268 41 260 58 250 66ZM199 64C177 42 190 23 199 15C216 38 207 54 199 64ZM191 105C211 104 225 87 224 70C201 73 189 85 191 105ZM110 165C82 172 59 152 61 143C86 136 104 150 110 165ZM91 134C113 115 98 97 96 89C76 104 80 123 91 134ZM76 107C47 103 44 81 46 72C71 77 79 90 76 107ZM199 237C201 216 222 202 234 210C229 229 212 239 199 237ZM228 215C252 224 270 211 273 202C254 192 237 204 228 215ZM255 189C250 167 269 153 278 155C280 175 265 188 255 189Z" fill="currentColor" fillOpacity=".10"/></g></svg>}
function Modal({children,onClose,label,wide=false}:{children:ReactNode;onClose:()=>void;label:string;wide?:boolean}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const prev=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button,input,textarea,select,a[href],[tabindex="0"]')||[]).filter(el=>!el.hasAttribute('disabled'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);prev?.focus()}},[onClose]);return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={ref} className={'modal '+(wide?'wide':'')} role="dialog" aria-modal="true" aria-label={label} tabIndex={-1}>{children}</div></div>}
function EntryCard({entry,onOpen,onFavorite,list=false,order=0}:{entry:Entry;order?:number;onOpen:()=>void;onFavorite:()=>void;list?:boolean}){const d=new Date(entry.date+'T12:00:00');return <article style={{order}} className={'entry-card '+(entry.cover?'featured ':'')+(list?'list-card':'')}><button className="card-open" onClick={onOpen} aria-label={'阅读：'+entry.title}>{entry.cover&&<div className="entry-cover"><img src="/garden.jpg" alt="阳光穿过茂密的绿色森林"/><span>把生活，过成喜欢的样子。</span></div>}<div className="card-content"><div className="entry-date"><span>{d.getMonth()+1} 月 {d.getDate()} 日 <span className="weekday">{['周日','周一','周二','周三','周四','周五','周六'][d.getDay()]}</span></span><span className="weather">{entry.weather==='小雨'?<CloudRain size={13}/>:<Sun size={13}/>} {entry.weather}</span></div><h3>{entry.title}</h3><p>{entry.body}</p></div></button><div className="card-footer"><div className="entry-tags"><span className="mood-tag">{entry.mood==='开心'?'☀':'◡'} {entry.mood}</span>{entry.tags.slice(0,2).map(t=><span key={t}>#{t}</span>)}</div><button className={'icon-btn bookmark '+(entry.favorite?'active':'')} aria-label={(entry.favorite?'取消收藏：':'收藏：')+entry.title} onClick={onFavorite}><Bookmark size={16} fill={entry.favorite?'currentColor':'none'}/></button></div></article>}
export default function App(){
 const initial=useMemo(readEntries,[]);
 const [entries,setEntries]=useState<Entry[]>(initial.entries);const [storageError,setStorageError]=useState(initial.error);
 const [view,setView]=useState<View>('all');const [query,setQuery]=useState('');const [tag,setTag]=useState('');const [mood,setMood]=useState('');const [selectedDate,setSelectedDate]=useState('');
 const [variant,setVariant]=useState(()=>{const v=new URLSearchParams(location.search).get('variant');return variants.includes(v||'')?v!:'A'});
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
 const [list,setList]=useState(false);const [editing,setEditing]=useState<Entry|null|undefined>(undefined);const [reading,setReading]=useState<Entry|null>(null);const [settings,setSettings]=useState(false);const [deleteId,setDeleteId]=useState<string|null>(null);const [mobileNav,setMobileNav]=useState(false);
 const [toast,setToast]=useState('');const [online,setOnline]=useState(navigator.onLine);const [install,setInstall]=useState<InstallEvent|null>(null);const [session,setSession]=useState<Session|null>(null);const [email,setEmail]=useState('');const [busy,setBusy]=useState(false);const [cloudMessage,setCloudMessage]=useState('');const [updateApp,setUpdateApp]=useState<((reload?:boolean)=>Promise<void>)|null>(null);
 const fileRef=useRef<HTMLInputElement>(null);
 const notify=useCallback((message:string)=>setToast(message),[]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(timer)}},[toast]);
 useEffect(()=>{const onlineFn=()=>setOnline(navigator.onLine);const installFn=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent)};window.addEventListener('online',onlineFn);window.addEventListener('offline',onlineFn);window.addEventListener('beforeinstallprompt',installFn);const done=()=>setInstall(null);window.addEventListener('appinstalled',done);return()=>{window.removeEventListener('online',onlineFn);window.removeEventListener('offline',onlineFn);window.removeEventListener('beforeinstallprompt',installFn);window.removeEventListener('appinstalled',done)}},[]);
 useEffect(()=>{const update=registerSW({onNeedRefresh(){setUpdateApp(()=>update)},onOfflineReady(){notify('离线书页已备好，断网也可以写日记。')}})},[notify]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data,error})=>{if(error)setCloudMessage(error.message);else setSession(data.session)});const {data}=supabase.auth.onAuthStateChange((_event,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 const changeVariant=useCallback((n:number)=>{setVariant(v=>{const next=variants[(variants.indexOf(v)+n+3)%3];const url=new URL(location.href);url.searchParams.set('variant',next);history.replaceState(null,'',url);return next})},[]);
 useEffect(()=>{if(!import.meta.env.DEV||!location.pathname.startsWith('/prototype'))return;const key=(e:KeyboardEvent)=>{if(editing!==undefined||reading||settings||deleteId)return;if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();changeVariant(e.key==='ArrowLeft'?-1:1)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[changeVariant,editing,reading,settings,deleteId]);
 useEffect(()=>{if(import.meta.env.DEV)console.info('[Ephemera prototype]',{variant,layout:variantNames[variants.indexOf(variant)],view,tag,mood,selectedDate,entries:entries.length,storage:'local prototype store',supabaseConfigured:Boolean(supabase)})},[variant,view,tag,mood,selectedDate,entries.length]);
 const persist=(next:Entry[])=>{if(storageError){notify('请先导出原始备份，再恢复数据，避免覆盖原有日记。');return false}try{localStorage.setItem(STORE,JSON.stringify(next));setEntries(next);return true}catch{notify('保存失败：浏览器存储空间不足或不可用。文字仍留在编辑器中。');return false}};
 const save=(entry:Entry)=>{const ok=persist([entry,...entries.filter(e=>e.id!==entry.id)]);if(ok)notify('日记已收好，保存在这台设备。');return ok};
 const favorite=(entry:Entry)=>{const changed={...entry,favorite:!entry.favorite,updated_at:new Date().toISOString()};if(persist(entries.map(e=>e.id===entry.id?changed:e))){if(reading?.id===entry.id)setReading(changed);notify(changed.favorite?'已夹进珍藏。':'已取消收藏。')}};
 const selectView=(v:View)=>{if(v!=='all'&&variant!=='A'){setVariant('A');const url=new URL(location.href);url.searchParams.set('variant','A');history.replaceState(null,'',url)}setView(v);setTag('');setMood('');setSelectedDate('');setMobileNav(false)};
 const tags=useMemo(()=>[...new Set(entries.flatMap(e=>e.tags))],[entries]);
 const filtered=useMemo(()=>entries.filter(e=>(view!=='favorites'||e.favorite)&&(!tag||e.tags.includes(tag))&&(!mood||e.mood===mood)&&(!selectedDate||e.date===selectedDate)&&(!query||`${e.title} ${e.body} ${e.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.date.localeCompare(a.date)||b.updated_at.localeCompare(a.updated_at)),[entries,view,tag,mood,selectedDate,query]);
 const today=localDate();const actual=entries.filter(e=>!e.id.startsWith('sample-'));const hasSamples=entries.some(e=>e.id.startsWith('sample-'));
 const closeEditor=useCallback(()=>setEditing(undefined),[]);const closeReader=useCallback(()=>setReading(null),[]);const closeSettings=useCallback(()=>setSettings(false),[]);const closeDelete=useCallback(()=>setDeleteId(null),[]);
 const exportData=(raw=false)=>{let body:string;try{body=raw?(localStorage.getItem(STORE)||'[]'):JSON.stringify({app:'芸窗 Ephemera',version:1,exportedAt:new Date().toISOString(),entries},null,2)}catch{notify('浏览器拒绝读取存储，无法导出。');return}const url=URL.createObjectURL(new Blob([body],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`芸窗-${raw?'原始备份-':''}${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('日记备份已导出。')};
 const importData=async(file:File)=>{if(file.size>5e6){notify('请选择小于 5 MB 的日记备份。');return}try{const parsed=JSON.parse(await file.text());const incoming=Array.isArray(parsed)?parsed:parsed.entries;if(!Array.isArray(incoming)||!incoming.every(entryValid))throw new Error();const merged=new Map(entries.map(e=>[e.id,e]));for(const e of incoming){const old=merged.get(e.id);if(!old||e.updated_at>old.updated_at)merged.set(e.id,e)}const next=[...merged.values()];if(storageError){localStorage.setItem(STORE+'-recovery-'+Date.now(),localStorage.getItem(STORE)||'');localStorage.setItem(STORE,JSON.stringify(next));setStorageError('');setEntries(next);notify('原数据已备份，日记已恢复。')}else if(persist(next))notify(`已合并 ${incoming.length} 篇日记。`)}catch{notify('无法导入，请使用芸窗导出的有效 JSON 备份。')}};
 const auth=async()=>{if(!supabase)return;if(!email.includes('@')){setCloudMessage('请输入有效的邮箱地址。');return}setBusy(true);try{const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin}});setCloudMessage(error?error.message:'登录链接已发送，请到邮箱中打开。')}catch{setCloudMessage('连接失败，请检查网络后重试。')}finally{setBusy(false)}};
 const cloudBackup=async(direction:'push'|'pull')=>{if(!supabase||!session)return;setBusy(true);setCloudMessage('');try{if(direction==='push'){if(!actual.length){setCloudMessage('先写一篇自己的日记，示例内容不会上传。');return}const {error}=await supabase.from('entries').upsert(actual.map(e=>({...e,user_id:session.user.id,cover:e.cover||false})));if(error)throw error;setCloudMessage(`已备份 ${actual.length} 篇日记到云端。`)}else{const {data,error}=await supabase.from('entries').select('*').eq('user_id',session.user.id);if(error)throw error;const merged=new Map(entries.map(e=>[e.id,e]));for(const row of data||[]){const {user_id:_,...e}=row;if(!entryValid(e))throw new Error('云端记录格式不匹配。');const old=merged.get(e.id);if(!old||e.updated_at>old.updated_at)merged.set(e.id,e)}if(persist([...merged.values()]))setCloudMessage(`已合并 ${data?.length||0} 篇云端日记。`)}}catch(e){setCloudMessage(e instanceof Error?e.message:'云端操作失败，请检查网络、配置与数据库权限。')}finally{setBusy(false)}};
 const installApp=async()=>{if(install){await install.prompt();await install.userChoice;setInstall(null)}else{setSettings(true);setCloudMessage('电脑：浏览器菜单中选择“安装芸窗”；iPhone：用 Safari 打开，分享 → 添加到主屏幕。需使用 HTTPS 或 localhost。')}};
 const renderCalendar=(large=false)=>{const start=(new Date(month.getFullYear(),month.getMonth(),1).getDay()+6)%7;const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return <div className={'calendar '+(large?'large-calendar':'')}><div className="calendar-heading"><span>{month.getFullYear()} 年 {month.getMonth()+1} 月</span><div><button className="icon-btn" aria-label="上个月" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft size={15}/></button><button className="icon-btn" aria-label="下个月" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight size={15}/></button></div></div><div className="calendar-grid">{['一','二','三','四','五','六','日'].map(w=><span className="week-label" key={w}>{w}</span>)}{Array.from({length:start},(_,i)=><span key={'blank'+i}/>)}{Array.from({length:count},(_,i)=>{const date=localDate(new Date(month.getFullYear(),month.getMonth(),i+1));const dayEntries=entries.filter(e=>e.date===date);return <button key={date} aria-label={`${date}${dayEntries.length?`，${dayEntries.length} 篇日记`:''}`} aria-pressed={selectedDate===date} className={(date===today?'today ':'')+(selectedDate===date?'chosen ':'')+(dayEntries.length?'has-entry':'')} onClick={()=>{setSelectedDate(d=>d===date?'':date);if(variant==='C')setVariant('A')}}><span>{i+1}</span>{large&&dayEntries[0]&&<small>{dayEntries[0].title}</small>}{dayEntries.length>0&&<i/>}</button>})}</div><div className="calendar-legend"><i/>有文字的日子，都在这里</div></div>};
 const renderCards=()=>filtered.length?<div className={'entries-grid '+(list?'as-list':'')}>{(list?[filtered]:[filtered.filter((_,i)=>i%2===0),filtered.filter((_,i)=>i%2===1)]).map((column,i)=><div className="entry-column" key={i}>{column.map(e=><EntryCard key={e.id} order={filtered.indexOf(e)} entry={e} onOpen={()=>setReading(e)} onFavorite={()=>favorite(e)} list={list}/>)}</div>)}</div>:<div className="empty-state"><Sprout size={36}/><h3>{query||tag||mood||selectedDate?'这一页，还没有找到文字':'故事，从今天开始'}</h3><p>{query||tag||mood||selectedDate?'换一个关键词，或放下筛选，看看其他日子。':'给今天留几句话，往后翻起，便是回忆。'}</p><button className="outline" onClick={()=>{if(query||tag||mood||selectedDate){setQuery('');setTag('');setMood('');setSelectedDate('')}else setEditing(null)}}>{query||tag||mood||selectedDate?'清除筛选':'写第一篇日记'}</button></div>;
 const sectionTitle=selectedDate?selectedDate.replaceAll('-',' / '):tag?`关于「${tag}」`:view==='favorites'?'值得珍藏的片刻':view==='moods'?'心情的四季':view==='calendar'?'沿着日历，翻回从前':'最近的日记';
 const filters=<>{(tag||mood||selectedDate)&&<button className="filter-chip" onClick={()=>{setTag('');setMood('');setSelectedDate('')}}>{tag||mood||selectedDate}<X size={12}/></button>}</>;
 const listHeading=<div className="section-heading"><div><h2>{sectionTitle}</h2><span>{filtered.length} 篇{hasSamples?' · 含示例日记':''}</span>{filters}</div><div className="view-toggle"><button aria-label="卡片视图" aria-pressed={!list} className={!list?'active':''} onClick={()=>setList(false)}><LayoutGrid size={16}/></button><button aria-label="列表视图" aria-pressed={list} className={list?'active':''} onClick={()=>setList(true)}><List size={17}/></button></div></div>;
 return <div className={'app variant-'+variant}>
 {mobileNav&&<div className="nav-scrim" onClick={()=>setMobileNav(false)}/>}
 <aside className={'sidebar '+(mobileNav?'mobile-open':'')}><a className="brand" href="/" onClick={e=>{e.preventDefault();selectView('all')}}><img src="/icon.svg" alt=""/><span><strong>芸窗</strong><em>Ephemera</em></span></a><div className="sidebar-intro">一扇窗，一本日记，一方心安。</div><button className="new-entry" onClick={()=>{setEditing(null);setMobileNav(false)}}><Plus size={18}/>写一篇日记<Feather size={17}/></button><div className="nav-label">我的书页</div><nav>{([{id:'all',icon:BookOpen,title:'所有日记',count:entries.length},{id:'calendar',icon:CalendarDays,title:'日历回顾'},{id:'favorites',icon:Bookmark,title:'我的珍藏',count:entries.filter(e=>e.favorite).length},{id:'moods',icon:Heart,title:'心情足迹'}] as const).map(n=><button key={n.id} className={view===n.id&&!tag?'selected':''} onClick={()=>selectView(n.id)}><n.icon size={18}/><span>{n.title}</span>{'count'in n&&<small>{n.count}</small>}</button>)}</nav><div className="tag-heading"><span className="nav-label">生活的切片</span><span>#</span></div><div className="sidebar-tags">{tags.map(t=><button key={t} className={tag===t?'selected':''} onClick={()=>{setTag(tag===t?'':t);setView('all');setMood('');setSelectedDate('');setMobileNav(false)}}><span>#</span>{t}</button>)}</div><div className="sidebar-poem"><Botanical small/><p>岁月不声不响，<br/>而你落笔有光。</p><span>Collect the little things.</span></div><div className="sidebar-bottom"><button onClick={()=>setSettings(true)}><span className="avatar">芸</span><span>我的小天地<small><i/>{online?'本机保存':'离线记录中'}</small></span><Settings size={17}/></button></div></aside>
 <div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-menu" aria-label="打开导航" onClick={()=>setMobileNav(true)}><Menu size={21}/></button><BookOpen size={16}/><span>{view==='all'?'我的日记':view==='calendar'?'日历回顾':view==='favorites'?'我的珍藏':'心情足迹'}</span><span className="breadcrumb-slash">/</span><span className="topbar-sub">记录生活，也照见自己</span></div><div className="topbar-actions"><label className="search"><Search size={16}/><input aria-label="搜索日记" placeholder="寻找一段回忆…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清除搜索" onClick={()=>setQuery('')}><X size={13}/></button>}</label><button className="icon-btn settings-btn" aria-label="设置与备份" onClick={()=>setSettings(true)}><Settings size={18}/></button></div></header>
 {storageError&&<div className="storage-warning" role="alert">{storageError}<button onClick={()=>exportData(true)}>导出原始备份</button></div>}
 {!online&&<div className="offline-banner"><WifiOff size={14}/>此刻离线，日记仍会保存在这台设备。</div>}
 {updateApp&&<div className="offline-banner">芸窗有新版本。请先收好正在写的日记。<button onClick={()=>updateApp(true)}>更新并重新打开</button></div>}
 <main>{variant==='A'&&<><section className="hero"><div className="hero-copy"><div className="hero-date"><span className="tiny-sun">✳</span>{new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}<span className="season">初秋手记</span></div><h1>把日子写成诗，<br/>把平凡留在心里。</h1><p>一些微小的欢喜，一些无处安放的心事。<br/>在这里，慢慢写，轻轻放。</p><button className="primary" onClick={()=>setEditing(null)}><Feather size={16}/>记下此刻<ArrowUpRight size={16}/></button></div><div className="hero-art"><div className="arch"><Botanical/><span className="vertical-quote">草木有本心 · 日常有微光</span></div><span className="art-caption">A little space for your everyday.</span><span className="stamp">芸<br/>窗</span></div></section><div className="desk-columns"><section className="diary-section">{view==='calendar'&&renderCalendar(true)}{view==='moods'&&<div className="mood-overview">{moods.map(m=><button className={mood===m?'selected':''} key={m} onClick={()=>setMood(mood===m?'':m)}><span>{m}</span><strong>{entries.filter(e=>e.mood===m).length}</strong><small>篇日记</small></button>)}</div>}{listHeading}{renderCards()}<p className="end-note">— 纸短情长，日子还在继续 —</p></section><aside className="right-rail">{renderCalendar()}<section className="daily-prompt"><div><Sprout size={17}/><h3>今日一问</h3></div><p>最近，有哪个微小的瞬间，<br/>让你觉得生活很可爱？</p><button onClick={()=>setEditing({id:crypto.randomUUID(),title:'一个让生活可爱的瞬间',body:'',date:today,mood:'平静',weather:'晴天',tags:['小确幸'],favorite:false,updated_at:new Date().toISOString()})}>从这里开始写<ArrowUpRight size={15}/></button><Leaf className="prompt-leaf" size={52}/></section><section className="journal-stats"><h3>与自己相处的时光</h3><div><span><strong>{entries.length}</strong><small>篇日记</small></span><span><strong>{new Set(entries.map(e=>e.date)).size}</strong><small>个有记录的日子</small></span></div><p>不必每天写，只要想起时，你在。</p></section><button className="install-card" onClick={installApp}><MonitorSmartphone size={23}/><span>把芸窗放在身边<small>添加到桌面，随时记录</small></span><ArrowUpRight size={15}/></button></aside></div></>}
 {variant==='B'&&<section className="timeline-layout"><header><span className="timeline-kicker">芸窗 · 时光长卷</span><h1>那些日子，<br/>后来都成了故事。</h1><p>沿着文字往回走，和某一天的自己重逢。</p><button className="primary" onClick={()=>setEditing(null)}><Plus size={16}/>添一页故事</button></header><div className="timeline-body"><div className="timeline-side">{renderCalendar()}<p>时间在走，<br/>而有些瞬间可以留下。</p></div><section className="timeline-entries">{listHeading}{filtered.length?filtered.map(e=><article className="timeline-row" key={e.id}><div className="timeline-day"><strong>{e.date.slice(-2)}</strong><span>{e.date.slice(0,7).replace('-',' / ')}</span></div><div className="timeline-story"><button onClick={()=>setReading(e)}><span>{e.mood} · {e.weather}</span><h2>{e.title}</h2><p>{e.body}</p>{e.cover&&<img src="/garden.jpg" alt="森林中的阳光"/>}</button><div><span>{e.tags.map(t=>'#'+t).join('　')}</span><button className="icon-btn" aria-label={(e.favorite?'取消收藏：':'收藏：')+e.title} onClick={()=>favorite(e)}><Bookmark size={16} fill={e.favorite?'currentColor':'none'}/></button></div></div></article>):renderCards()}</section></div></section>}
 {variant==='C'&&<section className="focus-layout"><div className="focus-heading"><span><Feather size={17}/>此刻，只管写</span><p>窗外的事，暂且放一放。</p></div><div className="focus-grid">{editing===undefined&&<Editor inline onClose={()=>{setVariant('A');const url=new URL(location.href);url.searchParams.set('variant','A');history.replaceState(null,'',url)}} onSave={save}/>}<aside><h3>书页索引</h3><p>回头看看走过的日子。</p>{filtered.map(e=><button className="focus-entry" key={e.id} onClick={()=>setReading(e)}><span>{e.date.replaceAll('-',' / ')}</span><strong>{e.title}</strong><small>{e.tags.map(t=>'#'+t).join(' ')}</small></button>)}{!filtered.length&&<p>还没有符合筛选的日记。</p>}<Botanical small/></aside></div></section>}
 <footer className="page-footer"><span>芸窗 Ephemera</span><span>让每一个平凡的日子，有迹可循。</span><span><Cloud size={13}/>{session?'已登录 · 手动云端备份':'文字存于本机'}</span></footer></main></div>
 <nav className="mobile-bottom"><button className={view==='all'?'active':''} onClick={()=>selectView('all')}><BookOpen size={19}/>日记</button><button onClick={()=>selectView('calendar')}><CalendarDays size={19}/>回顾</button><button className="mobile-write" aria-label="写日记" onClick={()=>setEditing(null)}><Plus size={24}/></button><button onClick={()=>selectView('favorites')}><Bookmark size={19}/>珍藏</button><button onClick={()=>setSettings(true)}><Settings size={19}/>我的</button></nav>
 {import.meta.env.DEV&&location.pathname.startsWith('/prototype')&&<div className="prototype-switcher"><span>原型</span><button aria-label="上一个设计方案" onClick={()=>changeVariant(-1)}><ChevronLeft size={17}/></button><strong>{variant} · {variantNames[variants.indexOf(variant)]}</strong><button aria-label="下一个设计方案" onClick={()=>changeVariant(1)}><ChevronRight size={17}/></button></div>}
 {editing!==undefined&&<Modal wide label="写日记" onClose={closeEditor}><Editor entry={editing||undefined} onClose={closeEditor} onSave={save}/></Modal>}
 {reading&&<Modal wide label={reading.title} onClose={closeReader}><article className="reader"><div className="reader-top"><button className="text-btn" onClick={closeReader}><ArrowLeft size={16}/>回到书页</button><div><button className="icon-btn" aria-label="编辑这篇日记" onClick={()=>{setEditing(reading);setReading(null)}}><Pencil size={17}/></button><button className="icon-btn" aria-label="收藏这篇日记" onClick={()=>favorite(reading)}><Bookmark size={17} fill={reading.favorite?'currentColor':'none'}/></button><button className="icon-btn" aria-label="删除这篇日记" onClick={()=>setDeleteId(reading.id)}><Trash2 size={17}/></button><button className="icon-btn" aria-label="关闭日记" onClick={closeReader}><X size={20}/></button></div></div>{reading.cover&&<img className="reader-cover" src="/garden.jpg" alt="阳光透过森林"/>}<div className="reader-text"><span className="reader-date">{reading.date.replaceAll('-',' / ')}　·　{reading.weather}　·　{reading.mood}</span><h1>{reading.title}</h1><div className="reader-body">{reading.body}</div><div className="reader-tags">{reading.tags.map(t=><span key={t}>#{t}</span>)}</div><div className="reader-end"><Leaf size={20}/><span>{reading.body.replace(/\s/g,'').length} 字，都是生活的回声。</span></div></div></article></Modal>}
 {settings&&<Modal label="我的小天地" onClose={closeSettings}><section className="settings"><div className="dialog-heading"><h2>我的小天地</h2><button className="icon-btn" aria-label="关闭设置" onClick={closeSettings}><X size={20}/></button></div><p className="muted">照料你的书页，也照料那些珍贵的日常。</p><div className="setting-section"><h3><Cloud size={18}/>云端备份</h3>{!supabase?<><p>当前为本机模式，日记保存在这个浏览器。清除浏览器数据会移除日记，请定期导出备份。</p><div className="connection-status"><i/>尚未连接云端</div><details><summary>连接 Supabase</summary><p>在项目 .env 中填写 VITE_SUPABASE_URL 和 VITE_SUPABASE_ANON_KEY，在测试项目运行 supabase/schema.sql，配置邮箱登录与重定向地址后重新构建。</p></details></>:session?<><p>已登录：{session.user.email}</p><p>主动备份到云端，在另一台设备登录后取回。示例日记不会上传；删除仅影响本机，云端备份仍会保留。</p><div className="button-row"><button className="outline" disabled={busy||!online} onClick={()=>cloudBackup('push')}><Upload size={15}/>上传本机日记</button><button className="outline" disabled={busy||!online} onClick={()=>cloudBackup('pull')}><Download size={15}/>取回云端日记</button></div><button className="text-btn" onClick={async()=>{const {error}=await supabase!.auth.signOut();setCloudMessage(error?error.message:'已退出，日记仍保留在本机。')}}><LogOut size={14}/>退出登录</button></>:<><p>使用邮箱登录，在自己的设备之间备份日记。</p><form onSubmit={e=>{e.preventDefault();void auth()}}><input type="email" required aria-label="登录邮箱" placeholder="你的邮箱地址" value={email} onChange={e=>setEmail(e.target.value)}/><button className="primary" disabled={busy||!online}><Mail size={16}/>{busy?'正在发送…':'发送登录链接'}</button></form></>}{cloudMessage&&<p className="cloud-message" role="status">{cloudMessage}</p>}</div><div className="setting-section"><h3><BookOpen size={18}/>带走你的文字</h3><p>导出完整 JSON 备份；导入时按日记 ID 合并，保留更新时间较新的内容。</p><div className="button-row"><button className="outline" onClick={()=>exportData()}><Download size={16}/>导出日记</button><button className="outline" onClick={()=>fileRef.current?.click()}><Upload size={16}/>导入备份</button>{storageError&&<button className="outline" onClick={()=>exportData(true)}>导出原始备份</button>}</div><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)void importData(file);e.target.value=''}}/></div><div className="setting-section"><h3><MonitorSmartphone size={18}/>随时打开芸窗</h3><p>支持电脑和手机。首次在线打开后，已缓存的应用可离线使用。iPhone 请在 Safari 分享菜单中选择「添加到主屏幕」。</p><button className="outline" onClick={installApp}><Plus size={16}/>{install?'安装芸窗':'查看安装方式'}</button></div>{hasSamples&&<div className="setting-section"><h3><Sprout size={18}/>从自己的故事开始</h3><p>书桌上的几篇文字是示例，帮助你感受芸窗。</p><button className="text-btn" onClick={()=>{if(persist(entries.filter(e=>!e.id.startsWith('sample-'))))notify('示例已收起，书页留给你的故事。')}}>清除示例日记</button></div>}<div className="settings-signature">芸窗 · Ephemera <span>原型 0.1</span></div></section></Modal>}
 {deleteId&&<Modal label="删除日记" onClose={closeDelete}><div className="confirm-dialog"><Trash2 size={25}/><h2>要与这一页告别吗？</h2><p>删除后无法撤销。若想留一份回忆，可以先在设置中导出备份。</p><div className="button-row"><button className="outline" onClick={closeDelete}>再留一会儿</button><button className="danger" onClick={()=>{if(persist(entries.filter(e=>e.id!==deleteId))){setDeleteId(null);setReading(null);notify('这篇日记已从本机删除。')}}}>删除这篇日记</button></div></div></Modal>}
 {toast&&<div className="toast" role="status"><Check size={17}/>{toast}<button className="icon-btn" aria-label="关闭提示" onClick={()=>setToast('')}><X size={14}/></button></div>}
 </div>
}
